###

GET http://localhost:3000/getVeicles

###

POST  http://localhost:3000/addNewVehicle
Content-Type: application/json

{
        "Type":["truck", "electric car"],   
        "ModelName":"chevrolet aveo",
        "LicenseNumber" :15022301,
        "AvailablEnergyPercentage":20,
        "MaximumTirePressure":70,
        "InflateTire" :40,
        "AddEnergy":30,
        "EnergySource": ["blabla", "blabla2"],  
        "Wheels":[20, 30, 50, 60, 30, 10]
}

###

GET http://localhost:3000/getVehicleByLicense/15022301

###

GET http://localhost:3000/getVehiclesFromSorting

###

POST http://localhost:3000/infalteTiresToMax

###

POST http://localhost:3000/addEnergyByLicense/15022301

###