###

GET http://localhost:3000/getVeicles

###

POST  http://localhost:3000/addNewVehicle
Content-Type: application/json

{
        "Type":["1111", "1212"],   
        "ModelName":"heythere1",
        "LicenseNumber" :200,
        "AvailablEnergyPercentage":100,
        "MaximumTirePressure":100,
        "InflateTire" :100,
        "AddEnergy":40,
        "EnergySource": "blabla",  
        "Wheels":[20, 30, 50, 60, 30, 10]
}

###

GET http://localhost:3000/getVehicleByLicense/10

###
GET http://localhost:3000/getVehicleFromFreeSearch/2
###

GET http://localhost:3000/getVehiclesFromSorting

###

GET http://localhost:3000/infalteTiresToMax

###